### ISSUE TITLE
Provider Class

### ISSUE THREAD

**Issue by yves-ledermann** [ClouDNS/octodns_cloudns#1]
Hi
i have to use `class: octodns_cloudns.ClouDNSProvider` instead of `octodns.provider.cloudns.ClouDNSProvider`
or i got the error `octodns.manager.ManagerException: Unknown provider class: octodns.provider.cloudns.ClouDNSProvider`
is that something worng on my side or does the readme and the docs need some update?

(installed via pip: `pip install octodns_cloudns`)

**Comment by Venkoul99** [comment]
Hello,

You can use class: `octodns_cloudns.ClouDNSProvider` if the ClouDNS provider(the __init__.py file downloaded with `pip install octodns_cloudns`) is not pasted in the providers folder in octodns(Step 3 from [our wiki](https://www.cloudns.net/wiki/article/509)). If the file is not pasted in the provider folder, it will not be found with `octodns.provider.cloudns.ClouDNSProvider`. This line says that you want to work with ClouDNS provider. It does not matter which way you initialize the provider, it will work the same in both ways.
