### ISSUE TITLE
TXT records need additional escaping

### ISSUE THREAD

**Issue by devpikachu** [ClouDNS/octodns_cloudns#2]
When creating a TXT record with a `+` in its value (eg. DKIM keys), it needs to be manually URL-encoded as `%2B`. This causes octoDNS to want to update the record every time, even though its value hasn't changed.

Sending a `+` makes a whitespace appear in its place, whilst sending it as `\+` makes it disappear completely.

**Comment by Venkoul99** [comment]
Hello,

Is it possible to provide the zone config file with the records that is applied so we can check further?

**Comment by Venkoul99** [comment]
Hello @devpikachu ,

We have released a new PIPY version of our octodns provider - 0.0.4 where the issues should be fixed.

You can update the octodns provider and proceed with the DNS records creation.

Please, do not hesitate to contact us if you experience any problems.
