### ISSUE TITLE
TXT records trailing dot

### ISSUE THREAD

**Issue by devpikachu** [ClouDNS/octodns_cloudns#3]
When creating TXT records, the value is set without a trailing dot (`.`). On a subsequent run, octoDNS will prompt to update the record as ClouDNS returns a trailing dot for the record. Attempting to perform this update then duplicates the record in ClouDNS.

Trying to set the record with a trailing dot from the get-go results in an infinite loop where more and more dots are added each time.

**Comment by Venkoul99** [comment]
Hello,

Is it possible to provide the zone config file with the records that is applied so we can check further?

**Comment by devpikachu** [comment]
Hello @Venkoul99! I'm attaching the requested files here. This includes those for #2 as it's the same setup, so I didn't duplicate them uselessly.

These files are the zone as exported from ClouDNS before any changes, i.e. the "manual" setup. Also included is the output of `octodns-sync`:
[zone-before.txt](https://github.com/user-attachments/fi
[octodns-before-check.txt](https://github.com/user-attachments/files/15891036/octodns-before-check.txt)
les/15891034/zone-before.txt)

These files are the zone exported after applying the above change and the diff from the first zone export to this one:
[zone-after.txt](https://github.com/user-attachments/files/15891052/zone-after.txt)
[zone-diff.txt](https://github.com/user-attachments/files/15891056/zone-diff.txt)

The output of `octodns-sync` after the change has been applied, to get an idea of what it sees different (the config wasn't changed after having applied it, only ran `octodns-sync` without `--doit`):
[octodns-after-check.txt](https://github.com/user-attachments/files/15891068/octodns-after-check.txt)

Finally, here's the config files themselves:
[config.yaml.txt](https://github.com/user-attachments/files/15891087/config.yaml.txt)
[omnilium.org.yaml.txt](https://github.com/user-attachments/files/15891081/omnilium.org.yaml.txt)

I've also left the `omnilium.org` zone under my account as was left by `octodns-sync --doit` as part of this test, should that help you.

**Comment by Venkoul99** [comment]
Hello @devpikachu ,

We have released a new PIPY version of our octodns provider - 0.0.4 where the issues should be fixed.

You can update the octodns provider and proceed with the DNS records creation.

Please, do not hesitate to contact us if you experience any problems.
